server:
  port: 8082
  servlet:
    context-path: /config
eureka:
  instance:
    hostname: localhost
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/register-eureka/eureka/
spring:
  application:
    name: CONFIG
logging:
  level: debug