server:
  port: 8090
  servlet:
    context-path: /account
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ebook?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        format_sql: true
#eureka
eureka:
  instance:
    hostname: 47.114.33.113
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/register-eureka/eureka/