server:
  port: 8086
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://47.114.33.113/register-eureka/eureka/
