server:
  port: 8084
  servlet:
    context-path: /producer
spring:
  application:
    name: PRODUCER
eureka:
  instance:
    hostname: 47.114.33.113
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/register-eureka/eureka/