server:
  port: 8084
  servlet:
    context-path: /producer
spring:
  application:
    name: producer-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://47.114.33.113/register-eureka/eureka/